languages:
  Ruby: true
  JavaScript: false
  Python: true
  PHP: false
engines:
 radon:
  enabled: true
ratings:
  paths:
    - "**.py"
exclude_paths:
- "docs/*"
- "jenkins_jobs/*"
- "emulators/cbench/*"
- "emulators/mt_cbench/*"
- "controllers/*"
