branches:
  only:
    - master
sudo: required
dist: trusty
language: python
python:
  - 3.4
jdk:
  - openjdk7
before_script:
  - sudo apt-get update -qq
  - sudo apt-get -y install openjdk-7-jdk openjdk-7-jre
  - sudo bash ./vagrant/base/provisioning/provision.sh
  - sudo apt-get -y install ssh
  - sudo useradd -s /bin/bash -m -G sudo jenkins
  - echo -e "jenkins" | passwd jenkins
  - sudo pip3 install paramiko
  - sudo pip2 install paramiko
  - sudo pip2 install bottle
  - sudo pip2 install requests --upgrade
  - sudo pip3 install requests --upgrade
  - sudo pip install requests --upgrade
  - sudo pip3 install coveralls
script:
  - echo "Running Unittests"
  - cd util/unittests
  - coverage erase
  - coverage run --omit='/usr/local/lib/python3.4/*' --include='../*.py' --parallel-mode test_stats.py
  - coverage run --omit='/usr/local/lib/python3.4/*' --include='../*.py' --parallel-mode test_cpu.py
  - coverage run --omit='/usr/local/lib/python3.4/*' --include='../*.py' --parallel-mode test_customsubprocess.py
  - coverage run --omit='/usr/local/lib/python3.4/*' --include='../*.py' --parallel-mode test_numeric.py
  - coverage run --omit='/usr/local/lib/python3.4/*' --include='../*.py' --parallel-mode test_process.py
  - coverage run --omit='/usr/local/lib/python3.4/*' --include='../*.py' --parallel-mode test_file.py
  - coverage run --omit='/usr/local/lib/python3.4/*' --include='../*.py' --parallel-mode test_sysstats.py
  - coverage run --omit='/usr/local/lib/python3.4/*' --include='../*.py' --parallel-mode test_html.py
  - coverage run --omit='/usr/local/lib/python3.4/*' --include='../*.py' --parallel-mode test_process.py
  - coverage run --omit='/usr/local/lib/python3.4/*' --include='../*.py' --parallel-mode test_netutil.py
  - coverage run --omit='/usr/local/lib/python3.4/*' --include='../*.py' --parallel-mode ../../stress_test/nstat_orchestrator.py --help
  - coverage combine
after_success:
  coveralls
