sudo: required
dist: trusty
language: python
python:
  - "3.4"
branches:
  only:
    - develop_release_1.1
install:
  - pip install bottle
  - pip install requests
  - pip install matplotlib
  - pip install lxml
  - pip install paramiko
  - apt-get update
  - apt-get install -y snmp snmpd libpcap-dev autoconf make automake libtool libconfig-dev
  - apt-get install -y openssh-client openssh-server openjdk-7-jdk
script: ./run_tests.sh
