# Copyright (c) 2015 Intracom S.A. Telecom Solutions. All rights reserved.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License v1.0 which accompanies this distribution,
# and is available at http://www.eclipse.org/legal/epl-v10.html

# ------------------------------------------------------------------------------

sudo: required
dist: trusty
branches:
  only:
    - develop_release_1.1
install:
  - sudo apt-get update
  - sudo apt-get install -y python python3.4 python-pip python3-pip
  - sudo apt-get install -y python3-bottle python3-requests python3-matplotlib python3-lxml python-lxml python-bottle python-requests python-matplotlib
  - sudo apt-get install -y snmp snmpd libpcap-dev autoconf make automake libtool libconfig-dev
  - sudo apt-get install -y openssh-client openssh-server openjdk-7-jdk
  - sudo pip install requests --upgrade
  - sudo pip3 install requests --upgrade
  - sudo pip install paramiko --upgrade
  - sudo pip3 install paramiko --upgrade
  - sudo pip install bottle --upgrade
script: ./run_tests.sh
notifications:
  email:
    - nstat@intracom-telecom.com
