language: python
python:
  - "3.4"
branches:
  only:
    - develop_release_1.1
install:
  - pip install bottle
  - pip install requests
  - pip install matplotlib
  - pip install lxml
  - pip install paramiko
script: ./run_tests.sh
