branches:
  only:
    - master
sudo: required
dist: trusty
language: python
python:
  - 3.4
jdk:
  - openjdk7
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install openjdk-7-jdk openjdk-7-jre
  - sudo bash ./vagrant/base/provisioning/provision.sh
  - sudo pip3 install paramiko
  - sudo pip2 install paramiko
  - sudo pip2 install bottle
  - sudo pip2 install requests --upgrade
  - sudo pip3 install requests --upgrade
  - sudo pip install requests --upgrade
  - sudo pip3 install coveralls
script:
  - echo "Running Unittests"
  - cd util/unittests
  - coverage erase
  - coverage run --omit='/usr/local/lib/python3.4/*' --include=$WORKSPACE/*.py --parallel-mode stats_test.py
  - coverage run --omit='/usr/local/lib/python3.4/*' --include=$WORKSPACE/*.py --parallel-mode cpu_test.py
  - coverage run --omit='/usr/local/lib/python3.4/*' --include=$WORKSPACE/*.py --parallel-mode customsubprocess_test.py
  - coverage run --omit='/usr/local/lib/python3.4/*' --include=$WORKSPACE/*.py --parallel-mode numeric_test.py
  - coverage run --omit='/usr/local/lib/python3.4/*' --include=$WORKSPACE/*.py --parallel-mode process_test.py
  - coverage run --omit='/usr/local/lib/python3.4/*' --include=$WORKSPACE/*.py --parallel-mode file_test.py
  - coverage run --omit='/usr/local/lib/python3.4/*' --include=$WORKSPACE/*.py --parallel-mode sysstats_test.py
  - coverage run --omit='/usr/local/lib/python3.4/*' --include=$WORKSPACE/*.py --parallel-mode html_test.py
  - coverage run --omit='/usr/local/lib/python3.4/*' --include=$WORKSPACE/*.py --parallel-mode process_test.py
  - coverage combine
after_success:
  coveralls
