sudo: required
dist: trusty
language: bash
jdk:
  - openjdk7
before_script:
    - sudo bash ./vagrant/base/provisioning/provision.sh
script:
    - echo "running a functional test"
    - bash ./run_tests.sh
