sudo: required
dist: trusty
language: bash
jdk: oraclejdk7
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install oracle-java7-installer
before_script:
  - sudo bash ./vagrant/base/provisioning/provision.sh
script:
  - echo "running a functional test"
  - bash ./run_tests.sh
